compressionLevel: mixed

enableGlobalCache: false

ignorePath: true

injectEnvironmentFiles:
  - .env.yarn?
  - .env.yarn.local?

nodeLinker: node-modules

npmAlwaysAuth: false

npmPublishAccess: public

npmScopes:
  ivy-chess:
    npmAuthToken: '${NPM_TOKEN-""}'

yarnPath: .yarn/releases/yarn-4.0.1.cjs
