compressionLevel: mixed

enableGlobalCache: false

injectEnvironmentFiles:
  - .env.yarn
  - .env.yarn.local?

nodeLinker: node-modules

npmAlwaysAuth: false

npmPublishAccess: public

npmScopes:
  ivy-chess:
    npmAuthToken: '${NPM_TOKEN}'

ignorePath: true

yarnPath: .yarn/releases/yarn-4.0.0-rc.53.cjs
