version: '3.9'
services:
  s3:
    image: 'minio/minio:latest'
    container_name: 'minio-s3-host'
    command: 'server /data --console-address ":9001"'
    environment:
      - MINIO_ROOT_USER=demo
      - MINIO_ROOT_PASSWORD=password123
    volumes:
      - ivy-evc-store:/data
    ports:
      - '9000:9000'
      - '9001:9001'
  redis:
    image: 'redis:latest'
    container_name: 'redis'
    command: 'redis-server --save 60 1 --loglevel warning'
    ports:
      - '6379:6379'
    volumes:
      - redis-store:/data
volumes:
  ivy-evc-store:
  redis-store:
