apiVersion: v1
kind: Secret
metadata:
  name: admin-credentials
stringData:
  ADMIN_EMAIL: {{ required "Please provide 'Secrets.adminEmail'" .Values.Secrets.adminEmail | quote }}
  ADMIN_PASSWORD: {{ required "Please provide 'Secrets.adminPassword'" .Values.Secrets.adminPassword | quote }}
