apiVersion: v1
kind: Secret
metadata:
  name: minio-access
stringData:
  S3_ACCESS_ID: {{ required "Please provide 'Secrets.minioAccessID'" .Values.Secrets.minioAccessID | quote }}
  S3_SECRET_KEY: {{ required "Please provide 'Secrets.minioKey'" .Values.Secrets.minioKey | quote }}
