apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
stringData:
  username: {{ required "Please provide 'Secrets.minioRootUser'" .Values.Secrets.minioRootUser | quote }}
  password: {{ required "Please provide 'Secrets.minioRootPassword'" .Values.Secrets.minioRootPassword | quote }}
