apiVersion: v1
kind: Secret
metadata:
  name: supabase-access
stringData:
  JWT_SECRET: {{ required "Please provide 'Secrets.jwtSecret'" .Values.Secrets.jwtSecret | quote }}
  SUPABASE_KEY: {{ required "Please provide 'Secrets.supabaseKey'" .Values.Secrets.supabaseKey | quote }}
