{{- if .Values.TLS.enabled }}
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: ivy-tls
  namespace: default
data:
  tls.crt: {{ required "Please provide 'TLS.crt'" .Values.TLS.crt | quote }}
  tls.key: {{ required "Please provide 'TLS.key'" .Values.TLS.key | quote }}
{{- end }}
