apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
spec:
  serviceName: redis-svc
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:latest
          command:
            - 'redis-server'
          args:
            - '/conf/redis.conf'
          ports:
            - containerPort: 6379
              name: redis-port
          volumeMounts:
            - name: data
              mountPath: /data
            - name: conf
              mountPath: /conf
      volumes:
        - name: conf
          configMap:
            name: redis-cnf
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        storageClassName: manual
        accessModes: ['ReadWriteOnce']
        resources:
          requests:
            storage: 5Gi
