apiVersion: v1
kind: Service
metadata:
  labels:
    app: gm
  name: gm-svc
spec:
  ports:
    - port: 4501
      protocol: TCP
      targetPort: 4501
      name: gm-http
    - port: 4502
      protocol: TCP
      targetPort: 4502
      name: gm-ws
  selector:
    app: gm
  type: ClusterIP
