apiVersion: v1
kind: Service
metadata:
  labels:
    app: evc
  name: evc-svc
spec:
  ports:
    - port: {{ .Values.Env.Ports.evc }}
      protocol: TCP
      targetPort: {{ .Values.Env.Ports.evc }}
  selector:
    app: evc
  type: ClusterIP
