apiVersion: v1
kind: Service
metadata:
  name: redisinsight-svc
  labels:
    app: redisinsight
spec:
  ports:
    - port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    app: redisinsight
  type: ClusterIP
