apiVersion: v1
kind: Service
metadata:
  labels:
    app: replays
  name: replays-svc
spec:
  ports:
    - port: 4505
      protocol: TCP
      targetPort: 4505
  selector:
    app: replays
  type: ClusterIP
