apiVersion: v1
kind: Service
metadata:
  labels:
    app: auth
  name: auth-svc
spec:
  ports:
    - port: {{ .Values.Env.Ports.auth }}
      protocol: TCP
      targetPort: {{ .Values.Env.Ports.auth }}
  selector:
    app: auth
  type: ClusterIP
