apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio
spec:
  serviceName: s3-svc
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: quay.io/minio/minio:latest
          command:
            - /bin/bash
            - -c
          args:
            - minio server /data --console-address :9001 --address :9009
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: minio-credentials
                  key: username
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: minio-credentials
                  key: password
          ports:
            - containerPort: 9009
              name: data-port
            - containerPort: 9001
              name: admin-port
          volumeMounts:
            - name: data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        storageClassName: manual
        accessModes: ['ReadWriteOnce']
        resources:
          requests:
            storage: 10Gi
