apiVersion: v1
kind: Service
metadata:
  labels:
    app: stats
  name: stats-svc
spec:
  ports:
    - port: {{ .Values.Env.Ports.stats }}
      protocol: TCP
      targetPort: {{ .Values.Env.Ports.stats }}
  selector:
    app: stats
  type: ClusterIP
