apiVersion: v1
kind: ConfigMap
metadata:
  name: gm-cfg
data:
  GM_PORT: {{ .Values.Env.Ports.gmHttp | quote }}
  GM_PLAYER_PORT: {{ .Values.Env.Ports.gmPlayerWs | quote }}
  GM_SPECTATOR_PORT: {{ .Values.Env.Ports.gmSpectatorWs | quote }}
