apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gm
  name: gm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gm
  template:
    metadata:
      labels:
        app: gm
    spec:
      containers:
        - image: heth03/ivy:gm-latest
          imagePullPolicy: Always
          name: gm
          envFrom:
            - secretRef:
                name: supabase-access
            - configMapRef:
                name: gm-cfg
            - configMapRef:
                name: s3-cfg
            - configMapRef:
                name: redis-cfg
            - configMapRef:
                name: supabase-cfg
