apiVersion: v1
kind: Service
metadata:
  labels:
    app: gm
  name: gm-svc
spec:
  ports:
    - port: {{ .Values.Env.Ports.gmHttp }}
      protocol: TCP
      targetPort: {{ .Values.Env.Ports.gmHttp }}
      name: gm-http
    - port: {{ .Values.Env.Ports.gmWs }}
      protocol: TCP
      targetPort: 
      name: gm-ws
  selector:
    app: gm
  type: ClusterIP
