apiVersion: v1
kind: Service
metadata:
  labels:
    app: gm
  name: gm-svc
spec:
  ports:
    - port: {{ .Values.Env.Ports.gmHttp }}
      protocol: TCP
      targetPort: {{ .Values.Env.Ports.gmHttp }}
      name: gm-http
    - port: {{ .Values.Env.Ports.gmPlayerWs }}
      protocol: TCP
      targetPort: {{ .Values.Env.Ports.gmPlayerWs }}
      name: gm-player-ws
    - port: {{ .Values.Env.Ports.gmSpectatorWs }}
      protocol: TCP
      targetPort: {{ .Values.Env.Ports.gmSpectatorWs }}
      name: gm-spectator-ws
  selector:
    app: gm
  type: ClusterIP
